#!/usr/bin/env bash
action=$1
shift

if [ "$action" = "usage" ] ; then
    echo "  Add task with due:today"
    echo "    $(basename "$0") \"TASK\""
    echo ""
    exit
fi

task="$@"
if [[ "$task" == *" due:"* ]] ; then
    >&2 echo "Warning: $(basename "$0") got duplicate due date"
    "$TODO_FULL_SH" command add "$task"
else
    "$TODO_FULL_SH" command add "$task due:$(date -I)"
fi
