#!/usr/bin/env bash
action=$1
shift

if [ "$action" = "usage" ] ; then
    echo "  Add task with due:tomorrow"
    echo "    $(basename "$0") \"TASK\""
    echo ""
    exit
fi

date="$(date --date=tomorrow -I)"
task="$@"

if [[ "$task" == *" due:"* ]] ; then
    >&2 echo "error: $(basename "$0") got extra due date"
    exit 1
fi

"$TODO_FULL_SH" command add "$task due:$date"
