#!/usr/bin/env bash
action=$1
shift

if [ "$action" = "usage" ] ; then
    echo "  Add task with due:tomorrow and t:tomorrow"
    echo "    $(basename "$0") \"TASK\""
    echo ""
    exit
fi

DATE="$(date --date=tomorrow -I)"
task="$@"

if [[ "$task" == *" due:"* ]] || [[ "$task" == *" t:"* ]] ; then
    >&2 echo "error: $(basename "$0") got extra due date or threshold date"
    exit 1
fi

"$TODO_FULL_SH" command add "$task due:$DATE t:$DATE"
